### ISSUE TITLE
Progress tracking and assigned chapters

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#23]
This issue will be used as the main reference to what needs to be completed and what phase we're at. We also put who is responsible for what chapter/content. Multiple people can assign themselves to individual chapters.

## Who is assigned what for chapters and appendices

| Chapter/appendix | Assigned to |
|------------------|-------------|
| chapters/02-filesystem.Rmd | |
| chapters/03-package-setup.Rmd | |
| chapters/04-function-development.Rmd | |
| chapters/05-version-control-solo.Rmd | |
| chapters/06-code-correctness.Rmd | |
| chapters/07-build-management.Rmd | |
| chapters/08-documentation.Rmd | |
| chapters/09-package-website.Rmd | |
| chapters/10-community-involvement.Rmd | |
| chapters/11-version-control-workflow.Rmd | |
| chapters/12-project-management.Rmd | |
| chapters/13-package-release.Rmd | |
| chapters/14-team-package-dev.Rmd | |

# Progress tracking
## Completed project assignments (item 2 in #1)

- [ ] appendices/assignment.Rmd

## Completed chapter final exercises (item 3 in #1)

- [ ] chapters/02-filesystem.Rmd
- [ ] chapters/03-package-setup.Rmd
- [ ] chapters/04-function-development.Rmd
- [ ] chapters/05-version-control-solo.Rmd
- [ ] chapters/06-code-correctness.Rmd
- [ ] chapters/07-build-management.Rmd
- [ ] chapters/08-documentation.Rmd
- [ ] chapters/09-package-website.Rmd
- [ ] chapters/10-community-involvement.Rmd
- [ ] chapters/11-version-control-workflow.Rmd
- [ ] chapters/12-project-management.Rmd
- [ ] chapters/13-package-release.Rmd
- [ ] chapters/14-team-package-dev.Rmd

**Comment by mbonsma** [comment]
Chapters I feel (somewhat) comfortable working on:
- 04 Functions
- 08 Documentation
- 10 Community involvement
- 12 Project management

**Comment by k8hertweck** [comment]
I'd be best suited to work on any of the following chapters:

chapters/01-syllabus.Rmd 
chapters/02-filesystem.Rmd
chapters/05-version-control-solo.Rmd
chapters/10-community-involvement.Rmd
chapters/11-version-control-workflow.Rmd
chapters/12-project-management.Rmd
chapters/14-team-package-dev.Rmd

**Comment by cwickham** [comment]
Taking into account some places that it looks like @k8hertweck and @mbonsma have covered, I'm happy with any of:
chapters/03-package-setup.Rmd 
chapters/04-function-development.Rmd 
chapters/06-code-correctness.Rmd 
 chapters/07-build-management.Rmd
chapters/09-package-website.Rmd 
chapters/13-package-release.Rmd

**Comment by cwickham** [comment]
To get the ball rolling, I've snagged `chapters/03-package-setup.Rmd`.

**Comment by ian-flores** [comment]
Hey folks, sorry for the delay. I'm prefer to contribute with the following chapters:

- chapters/05-version-control-solo.Rmd
- chapters/07-build-management.Rmd
- chapters/08-documentation.Rmd
- chapters/09-package-website.Rmd
- chapters/13-package-release.Rmd

But I also feel comfortable contributing to any chapter as needed.

**Comment by lwjohnst86** [comment]
great, thanks all. I'll compare the differences and assign people to chapters before next meeting.

**Comment by lwjohnst86** [comment]
I've updated who's assigned to which chapter and I've also put each person with a primary chapter and a secondary chapter (so you would be responsible for reviewing, bouncing ideas of, etc). So far, each person has about 3 chapters for primary and two-three chapters as secondary.
